# Generated by Django 5.2.1 on 2025-06-02 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_jockey_birth_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jockey',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='jockey',
            name='cumulative_place_3',
        ),
        migrations.RemoveField(
            model_name='jockey',
            name='cumulative_place_rate_3',
        ),
        migrations.RemoveField(
            model_name='jockey',
            name='cumulative_runs',
        ),
        migrations.RemoveField(
            model_name='jockey',
            name='dirt_runs',
        ),
        migrations.RemoveField(
            model_name='jockey',
            name='dirt_wins',
        ),
        migrations.RemoveField(
            model_name='jockey',
            name='first_place',
        ),
        migrations.RemoveField(
            model_name='jockey',
            name='graded_race_runs',
        ),
        migrations.RemoveField(
            model_name='jockey',
            name='graded_race_wins',
        ),
        migrations.RemoveField(
            model_name='jockey',
            name='name',
        ),
        migrations.RemoveField(
            model_name='jockey',
            name='normal_race_runs',
        ),
        migrations.RemoveField(
            model_name='jockey',
            name='normal_race_wins',
        ),
        migrations.RemoveField(
            model_name='jockey',
            name='place_rate_2',
        ),
        migrations.RemoveField(
            model_name='jockey',
            name='place_rate_3',
        ),
        migrations.RemoveField(
            model_name='jockey',
            name='second_place',
        ),
        migrations.RemoveField(
            model_name='jockey',
            name='special_race_runs',
        ),
        migrations.RemoveField(
            model_name='jockey',
            name='special_race_wins',
        ),
        migrations.RemoveField(
            model_name='jockey',
            name='third_place',
        ),
        migrations.RemoveField(
            model_name='jockey',
            name='total_place_3',
        ),
        migrations.RemoveField(
            model_name='jockey',
            name='total_runs',
        ),
        migrations.RemoveField(
            model_name='jockey',
            name='turf_runs',
        ),
        migrations.RemoveField(
            model_name='jockey',
            name='turf_wins',
        ),
        migrations.RemoveField(
            model_name='jockey',
            name='unplaced',
        ),
        migrations.RemoveField(
            model_name='jockey',
            name='win_rate',
        ),
        migrations.RemoveField(
            model_name='jockey',
            name='year',
        ),
    ]
