# Generated by Django 5.2.1 on 2025-06-02 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_jockey_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='racedetail',
            name='horse_weight',
            field=models.TextField(blank=True, null=True),
        ),
    ]
