# Generated by Django 5.2.1 on 2025-06-02 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_racedetail_horse_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='racedetail',
            name='check_target',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
