# Generated by Django 5.2.1 on 2025-06-02 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_racedetail_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='racedetail',
            name='odds',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
